export type StellarPublicKey = string;

export interface Invoice {
  id: string;
  partnerName: string;
  industry: 'Logistics' | 'Technology' | 'Healthcare' | 'Energy' | 'Retail';
  amount: number;
  annualReturn: number; // as percentage, e.g. 12.5 for 12.5%
  dueDate: string;
  fundingProgress: number; // 0 to 100
  targetAmount: number;
  daysRemaining: number;
  status: 'Funded' | 'Pending' | 'Due Soon' | 'Paid';
  settlementStatus?: 'NotDue' | 'RepaymentPending' | 'RepaymentSubmitted' | 'Settling' | 'Settled' | 'Failed';
  settlementTxHash?: string;
  risk: 'Low Risk' | 'Moderate' | 'Stable';
  creatorWallet: StellarPublicKey;
}

export interface Activity {
  id: string;
  title: string;
  timestamp: string;
  amount?: string;
  type: 'approval' | 'repayment' | 'limit_update';
}

export type WalletProviderType = 'freighter' | 'albedo' | 'rabe' | 'manual_dev';

export interface WalletState {
  address: StellarPublicKey | null;
  provider: WalletProviderType | null;
  connected: boolean;
  role?: 'investor' | 'admin';
  network?: string; // Network reported by wallet (e.g. 'TESTNET' or 'PUBLIC')
}

export interface AuditTrailEntry {
  id: string;
  timestamp: string; // ISO string format
  eventId: string; // e.g. "CB-9021"
  eventName: string; // e.g. "Global Logistics Inc."
  actionType: 'Tokenization' | 'Risk Mutation' | 'Asset Funding' | 'Settlement';
  details: string;
  txHash?: string; // Stellar tx hash (or marked simulated)
  isSimulated?: boolean; // True if record was generated by prototype simulation
  operatorWallet: StellarPublicKey; // Wallet that executed the action
}

export type InvestmentStatus = 'Active' | 'Settled' | 'Defaulted';

export interface Investment {
  id: string; // Unique position identifier, e.g. "INV-178903-XXXX"
  invoiceId: string; // Relational foreign key referencing Invoice.id
  investorWallet: StellarPublicKey; // Stellar Ed25519 public key
  amount: number; // Principal invested in USD, 2 decimal places precision
  capturedApr: number; // APR % captured from invoice at investment time
  expectedYield: number; // Projected interest yield in USD (not yet earned/paid)
  expectedReturn: number; // Projected total repayment (principal + expectedYield) in USD
  timestamp: string; // ISO 8601 creation timestamp
  maturityDate: string; // Expected maturity date (aligned with invoice dueDate)
  status: InvestmentStatus; // Current position status
}

export interface InvestmentWithInvoice extends Investment {
  partnerName?: string;
  industry?: string;
  daysRemaining?: number;
  invoiceStatus?: 'Funded' | 'Pending' | 'Due Soon' | 'Paid';
  invoiceAmount?: number;
  ownershipPercentage?: number;
}

export interface InvestorPortfolioSummary {
  totalPrincipalInvested: number;
  totalExpectedYield: number;
  totalExpectedRepayment: number;
  weightedAverageApr: number;
  activePositionsCount: number;
  settledPositionsCount: number;
}

// --- Live Stellar Network Monitoring Types ---
export type StellarNetworkId = 'testnet' | 'public' | 'futurenet' | 'local';

export type StellarNetworkAvailability = 'healthy' | 'degraded' | 'unavailable';

export interface StellarLatestLedger {
  sequence: number;
  closedAt: string; // ISO 8601 string
  closeTimeSeconds: number; // e.g. 5.0 seconds
  baseFee: number; // in stroops (1 stroop = 0.0000001 XLM)
  txCount: number; // successful transaction count in the ledger
  operationCount?: number;
}

export interface StellarFeeStats {
  lastLedgerBaseFee: number; // in stroops
  minAcceptedFee: number; // in stroops
  modeAcceptedFee: number; // in stroops
  p50AcceptedFee: number; // in stroops
  capacityUsage: number; // float 0.0 - 1.0 representing capacity usage
}

export interface StellarNetworkStatus {
  network: StellarNetworkId;
  networkPassphrase: string;
  horizonUrl: string;
  explorerBaseUrl: string;
  status: StellarNetworkAvailability;
  latestLedger: StellarLatestLedger | null;
  feeStats: StellarFeeStats | null;
  protocolVersion: number | null;
  coreVersion?: string;
  horizonVersion?: string;
  fetchedAt: string; // ISO 8601 string of when CreditBridge queried Horizon
  isCached: boolean;
  isStale: boolean;
  latencyMs?: number;
  error?: string | null;
}

// --- Wallet & Transaction Infrastructure Types ---
export type WalletConnectionStatus = 
  | 'disconnected'
  | 'detecting'
  | 'connecting'
  | 'connected'
  | 'rejected'
  | 'not_installed'
  | 'network_mismatch'
  | 'error';

export interface StellarWalletProvider {
  id: WalletProviderType;
  name: string;
  description: string;
  isAvailable: () => Promise<boolean>;
  connect: () => Promise<{ address: string; network?: string }>;
  disconnect: () => Promise<void>;
  signTransaction: (xdr: string, opts?: { networkPassphrase?: string; address?: string }) => Promise<string>;
  getNetwork?: () => Promise<string>;
}

export interface TransactionPreparationResponse {
  unsignedXdr: string;
  network: StellarNetworkId;
  networkPassphrase: string;
  sourceAccount: string;
  sequence: string;
  baseFee: number;
  operationType: string;
  memo?: string;
}

export interface TransactionSubmissionResult {
  successful: boolean;
  hash: string;
  ledger?: number;
  network: StellarNetworkId;
  createdAt: string;
  explorerUrl: string;
  envelopeXdr?: string;
  resultXdr?: string;
  error?: string;
}

export interface AccountFundingStatus {
  isFunded: boolean;
  balanceXlm?: string;
  subentryCount?: number;
  address: string;
  network: StellarNetworkId;
}

// --- Invoice Repayment, Settlement & Distribution Lifecycle Types ---

export type InvoiceSettlementState = 
  | 'NotDue'
  | 'RepaymentPending'
  | 'RepaymentSubmitted'
  | 'Settling'
  | 'Settled'
  | 'Failed';

export type DistributionStatus = 
  | 'PendingDistribution' 
  | 'Settled' 
  | 'Failed';

export interface InvestorEntitlement {
  investmentId: string;
  investorWallet: StellarPublicKey;
  principal: number; // in USD cents-accurate
  capturedApr: number; // locked APR %
  expectedYield: number; // in USD
  totalEntitlement: number; // principal + expectedYield
  ownershipPercentage: number;
  distributionStatus: DistributionStatus;
  distributedAmount?: number;
  distributedAt?: string;
}

export interface SettlementCalculation {
  invoiceId: string;
  partnerName: string;
  invoiceAmount: number;
  totalPrincipalAllocated: number;
  totalYieldObligation: number;
  totalDistributionObligation: number;
  capturedApr: number;
  tenorDays: number;
  activeInvestorCount: number;
  netPlatformSurplus: number;
  entitlements: InvestorEntitlement[];
  calculatedAt: string;
}

export interface SettlementRecord {
  id: string; // e.g. "SETTLE-CB-8890-178900"
  invoiceId: string;
  debtorWallet: StellarPublicKey;
  amountDue: number;
  totalDistributed: number;
  status: InvoiceSettlementState;
  network: StellarNetworkId;
  stellarTxHash?: string;
  ledger?: number;
  explorerUrl?: string;
  entitlements: InvestorEntitlement[];
  createdAt: string;
  submittedAt?: string;
  settledAt?: string;
  failureReason?: string;
}

export interface RepaymentPreparationResponse {
  invoiceId: string;
  partnerName: string;
  amountDue: number;
  unsignedXdr: string;
  network: StellarNetworkId;
  networkPassphrase: string;
  sourceAccount: string;
  sequence: string;
  baseFee: number;
  settlementCalculation: SettlementCalculation;
}

